### ISSUE TITLE
read timeout on creating a remote driver leaving a chome process behind

### ISSUE THREAD

**Issue by mjegh** [teodesian/Selenium-Remote-Driver#294]
```
eval {
    $driver = Selenium::Remote::Driver->new('browser_name' =>'chrome', auto_close => 1);
};
if (my $ev = $@) {
    say "Failed to create selenium remote driver - $ev";
}
```
outputs "Failed to create selenium remote driver - Could not create new session: Server returned error message read timeout at /home/feed/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Net/HTTP/Methods.pm line 273, <DATA> line 1. instead of data at xxx"

and seems to leave a chrome lying around. How can this be avoided?

**Comment by mjegh** [comment]
Sorry, forgot to say:
$ perl -MSelenium::Remote::Driver -le 'print $Selenium::Remote::Driver::VERSION'
0.2701
$ perl --version
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)

**Comment by gempesaw** [comment]
Hi mjegh, can you also provide: chrome version, webdriver server version, chromedriver version? Thanks

**Comment by mjegh** [comment]
$ chromedriver --v
ChromeDriver 2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)

google chrome
Version 49.0.2623.110 (64-bit)

selenium-server-standalone-2.53.0.jar

**Comment by gempesaw** [comment]
hmm, is it possible for you to upgrade your chrome and [chromedriver](http://chromedriver.storage.googleapis.com/index.html) ? or, do you deliberately want to test using older versions?

**Comment by mjegh** [comment]
We are not that far behind on versions. This is a production environment and unless a bug is stopping something working it is generally not smiled upon upgrading without cause. I could try upgrading and running the code on a different machine but I don't hold out much hope of the problem going away as we've had it for a long time across loads of versions - it is just now it is worse and is impacting more.

Is there any way to try and diagnose what the timeout is?

**Comment by gempesaw** [comment]
oh, sure, just checking if there was an easy solution, as I haven't seen that issue locally on latest chrome/2.25 chromedriver/selenium3.0.1 on os x. 

Is the issue intermittent? The title and first comment don't mention it, but the most recent comment indicates that sometimes it works, but it's getting worse ? 

Well, when I have time I'll start by figuring out how to install an old chrome, I guess...hmmm...oh, there might be more useful information from:

- turning [debug on](https://metacpan.org/pod/Selenium::Remote::Driver#debug_on)... Hm, it'll be a little pain. Since the error's happening during startup, there's no chance to call the public function `debug_on` before the failure occurs. You'd have to find your Selenium::Remote::RemoteConnection PM file, get write permissions on it, and set the [default for `debug` to 1 instead of 0](https://github.com/gempesaw/Selenium-Remote-Driver/blob/c71530b82098f5d2bece18cc61dc7de6e6b777fd/lib/Selenium/Remote/RemoteConnection.pm#L25) ... (and remember to change it back afterwards). 

- the Selenium standalone server jar logs might have useful output, can you also provide that?

- You may also consider trying the `POST /session` yourself, and seeing if the behavior is the same:

        curl -X POST http://localhost:4444/wd/hub/session -d '{ "desiredCapabilities": { "browserName": "chrome" } }'

**Comment by mjegh** [comment]
The issue is intermittent. To give you some background the code runs approx every 5m from lunch time (ish) to around 9pm and accesses a web site collecting some information from it. After it has run a few days the machine starts going into swap big time because of the number of chrome processes left behind. After 2 days we can easily have 100 or so of them.

I'll look into your other suggestions and get back to you.

Thanks

**Comment by mjegh** [comment]
My selenium log file is 200MB and does not contain the string "read timeout". I'll truncate it and see when it happens again. Of course, since I created this issue in git, it hasn't happened - always the way.

**Comment by mjegh** [comment]
The only thing in the selenium error log at the time of the last timeout is:

5 minute gap in log file then the following when I got a timeout:

```
12:12:14.843 INFO - Executing: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, acceptSslCerts=true, browserName=chrome, version=}]])
12:12:14.845 INFO - Creating a new session for Capabilities [{platform=ANY, javascriptEnabled=true, acceptSslCerts=true, browserName=chrome, version=}]
Starting ChromeDriver 2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a) on port 25422
Only local connections are allowed.
```
then there is a 5m gap to the next time the code ran.

**Comment by mjegh** [comment]
The curl command you provided returns in around 5s but of course leaves loads of chrome processes lying around:

```
$ ps aux | grep chrome | wc -l
16
$ curl -X POST http://localhost:4444/wd/hub/session -d '{ "desiredCapabilities": { "browserName": "chrome" } }'
{"sessionId":"fc261034-8442-4f10-957d-f33139f50590","status":0,"state":null,"value":{"platform":"LINUX","acceptSslCerts":true,"javascriptEnabled":true,"browserName":"chrome","chrome":{"userDataDir":"/tmp/.com.google.Chrome.UQKdgY","chromedriverVersion":"2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)"},"rotatable":false,"locationContextEnabled":true,"mobileEmulationEnabled":false,"webdriver.remote.sessionid":"fc261034-8442-4f10-957d-f33139f50590","version":"49.0.2623.110","takesHeapSnapshot":true,"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"browserConnectionEnabled":false,"nativeEvents":true,"webStorageEnabled":true,"hasTouchScreen":false,"applicationCacheEnabled":false,"takesScreenshot":true},"class":"org.openqa.selenium.remote.Response","hCode":1723119202}
$ ps aux | grep chrome | wc -l
25
$ curl -X POST http://localhost:4444/wd/hub/session -d '{ "desiredCapabilities": { "browserName": "chrome" } }'
{"sessionId":"e50d94d9-b741-4845-a4cc-6e63b5184146","status":0,"state":null,"value":{"platform":"LINUX","acceptSslCerts":true,"javascriptEnabled":true,"browserName":"chrome","chrome":{"userDataDir":"/tmp/.com.google.Chrome.HbhY9y","chromedriverVersion":"2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)"},"rotatable":false,"locationContextEnabled":true,"mobileEmulationEnabled":false,"webdriver.remote.sessionid":"e50d94d9-b741-4845-a4cc-6e63b5184146","version":"49.0.2623.110","takesHeapSnapshot":true,"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"browserConnectionEnabled":false,"nativeEvents":true,"webStorageEnabled":true,"hasTouchScreen":false,"applicationCacheEnabled":false,"takesScreenshot":true},"class":"org.openqa.selenium.remote.Response","hCode":177796816}
$ ps aux | grep chrome | wc -l
32
```

**Comment by mjegh** [comment]
From selenium error log this morning when I got a timeout:

```
11:12:12.928 INFO - Executing: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, acceptSslCerts=true, browserName=chrome, version=}]])
11:12:12.930 INFO - Creating a new session for Capabilities [{platform=ANY, javascriptEnabled=true, acceptSslCerts=true, browserName=chrome, version=}]
Starting ChromeDriver 2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a) on port 15306
Only local connections are allowed.
11:13:15.014 INFO - Command failed to close cleanly. Destroying forcefully (v2). [/usr/bin/chromedriver, --port=15306][ {}]
11:13:16.026 ERROR - Unable to kill process with PID 1958
11:13:16.028 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'feed-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.7.0_95'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'feed-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.7.0_95'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor22.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
	... 9 more
Caused by: org.openqa.selenium.WebDriverException: chrome not reachable
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-30-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'feed-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.7.0_95'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
	... 13 more
11:13:16.034 WARN - Exception: chrome not reachable
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-30-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'feed-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.7.0_95'
Driver info: org.openqa.selenium.chrome.ChromeDriver
```

**Comment by mjegh** [comment]
The process mentioned does not exist now:

```
$ ps aux | grep 1958
feed      2361  0.0  0.0  15948  2320 pts/14   S+   11:17   0:00 grep --color=auto 1958
```
However, I have a chrome left behind now:

```
$ ps aux | grep chrome
feed      1977  0.0  0.5 349868 46464 pts/14   S    11:12   0:00 /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.qkXxFR
feed      1978  0.0  0.0 131300  5912 pts/14   S    11:12   0:00 /opt/google/chrome/nacl_helper
feed      1981  0.0  0.0 349868  8168 pts/14   S    11:12   0:00 /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.qkXxFR
feed      1984  0.5  0.1 329648 10440 pts/14   S    11:12   0:01 /opt/google/chrome/chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.com.google.Chrome.ZhsCPr/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12448 --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.qkXxFR data:,
feed      2408  0.0  0.0  15948  2320 pts/14   R+   11:18   0:00 grep --color=auto chrome
feed     12391  0.2  2.2 4605312 180072 pts/14 Sl   Nov17   2:16 /usr/bin/java -jar /usr/lib/headless-selenium/selenium-server-standalone-2.53.0.jar -Dwebdriver.chrome.driver=/usr/bin/chromedriver -port 4444
```

**Comment by mjegh** [comment]
I turned on the debug setting but it all comes out on stdout or stderr and this mixes with my script output which is really inconvenient. Any way to direct the debug to a file?

**Comment by mjegh** [comment]
I enabled debug in the remote driver and then turn if off once it succeeds. It appears the difference between a fail and a success is:

```
fail
REQ: GET, status, 
RES: {"sessionId":null,"status":0,"state":"success","value":{"build":{"version":"2.53.0","revision":"35ae25b","time":"2016-03-15 17:00:58"},"os":{"name":"Linux","arch":"amd64","version":"4.2.0-30-generic"},"java":{"version":"1.7.0_95"}},"class":"org.openqa.selenium.remote.Response","hCode":1844382877}

REQ: POST, session, {"desiredCapabilities":{"version":"","javascriptEnabled":true,"platform":"ANY","acceptSslCerts":true,"browserName":"chrome"}}
RES: read timeout at /home/xxx/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Net/HTTP/Methods.pm line 273, <DATA> line 1.
```

```
success
REQ: GET, status, 
RES: {"sessionId":null,"status":0,"state":"success","value":{"build":{"version":"2.53.0","revision":"35ae25b","time":"2016-03-15 17:00:58"},"os":{"name":"Linux","arch":"amd64","version":"4.2.0-30-generic"},"java":{"version":"1.7.0_95"}},"class":"org.openqa.selenium.remote.Response","hCode":1935230922}

REQ: POST, session, {"desiredCapabilities":{"version":"","browserName":"chrome","acceptSslCerts":true,"javascriptEnabled":true,"platform":"ANY"}}
RES: {"sessionId":"5a75c792-07cc-4c49-ab47-32790212d59c","status":0,"state":null,"value":{"platform":"LINUX","acceptSslCerts":true,"javascriptEnabled":true,"browserName":"chrome","chrome":{"userDataDir":"/tmp/.com.google.Chrome.4J64AD","chromedriverVersion":"2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a)"},"rotatable":false,"locationContextEnabled":true,"mobileEmulationEnabled":false,"webdriver.remote.sessionid":"5a75c792-07cc-4c49-ab47-32790212d59c","version":"49.0.2623.110","takesHeapSnapshot":true,"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"browserConnectionEnabled":false,"nativeEvents":true,"webStorageEnabled":true,"hasTouchScreen":false,"applicationCacheEnabled":false,"takesScreenshot":true},"class":"org.openqa.selenium.remote.Response","hCode":1947944320}
```

**Comment by gempesaw** [comment]
Blergh, sorry for the delay. #295 may be related - perhaps the remote driver machine is taking more than 180 seconds to create the webdriver browser? 

```perl
my $ua = LWP::UserAgent->new;
$ua->timeout(360);
my $d = Selenium::Remote::Driver->( ua => $ua );
```

But .... even if this _does_ help, I'm not sure if it's practical to wait that long for a browser...

**Comment by mjegh** [comment]
Thanks for that. I will start logging the time and see what it is when it fails.

**Comment by mjegh** [comment]
```
WARN [4] Failed to create selenium remote driver - Could not create new session: chrome not reachable
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 4.2.0-30-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 60.05 seconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'feed-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-30-generic', java.version: '1.7.0_95'
Driver info: org.openqa.selenium.chrome.ChromeDriver at xxx.pl line 149.
 END

TIME WAS 63
```

So it looks like the timeout is 60s. I'd prefer to give up sooner but this isn't an option if I leave a chome around. Guess I'll try increasing the timeout with your referenced trick first.

**Comment by mjegh** [comment]
and without changing the timeout at all a later one said "TIME WAS 181" so the timeout isn't even consistent.

**Comment by mjegh** [comment]
```
WARN [4] Failed to create selenium remote driver - Could not create new session: Server returned error message read timeout at /home/feed/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Net/HTTP/Methods.pm line 273, <DATA> line 1.
 instead of data at xx.pl line 149.
 END

WARN [4] If this keeps happening someone might want to follow http://andvari.easysoft.local/wiki/BET/Feeds/Horse_Racing#Problems_with_the_selenium_Server_for_WH END

TIME WAS 180
[ "25256 pts/14   Sl     0:00 /opt/google/chrome/chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.com.google.Chrome.87eZmY/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12774 --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.LvVY1X data:,
", "25269 pts/14   S      0:00 /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.LvVY1X
", "25270 pts/14   S      0:00 /opt/google/chrome/nacl_helper
", "25273 pts/14   S      0:00 /opt/google/chrome/chrome --type=zygote --enable-logging --log-level=0 --user-data-dir=/tmp/.com.google.Chrome.LvVY1X
", "25310 pts/14   Sl     0:00 /opt/google/chrome/chrome --type=gpu-process --channel=25256.0.997828738 --enable-logging --log-level=0 --window-depth=24 --user-data-dir=/tmp/.com.google.Chrome.LvVY1X --supports-dual-gpus=false --gpu-driver-bug-workarounds=3,54 --disable-accelerated-video-decode --gpu-vendor-id=0x80ee --gpu-device-id=0xbeef --gpu-driver-vendor --gpu-driver-version --user-data-dir=/tmp/.com.google.Chrome.LvVY1X --enable-logging --log-level=0 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
", "25327 pts/14   S      0:00 /opt/google/chrome/chrome --disable-background-networking --disable-client-side-phishing-detection --disable-component-update --disable-default-apps --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-logging --ignore-certificate-errors --load-extension=/tmp/.com.google.Chrome.87eZmY/internal --log-level=0 --metrics-recording-only --no-first-run --password-store=basic --remote-debugging-port=12774 --safebrowsing-disable-auto-update --safebrowsing-disable-download-protection --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.com.google.Chrome.LvVY1X data:,
" ]
```

The list is a list of processes left lying around afterwards - all chrome.

**Comment by teodesian** [comment]
If the server is under enough load that creating a new browser session times out, it is doubtful that if we issued a command to terminate the session that it would go through successfully.  As such I am reluctant to attempt to do anything outside of an eval {} about this; that would again simply mitigate the problem rather than stop it.

The actual solution here is to configure your selenium server to reap inactive sessions older than X minutes.  You should set the timeout to something slightly more than your test which has to wait on a UI the longest.  In our case, that was 30mins due to an incredibly poorly written comet interface, but in most cases 5mins should suffice.

I don't remember the option off the top of my head, but I can look it up tomorrow if you haven't figured it out by then.

**Comment by teodesian** [comment]
I might want to put something like this into a POD FAQ

**Comment by mjegh** [comment]
Thanks teodesian. I cannot seem to find an option to reap inactive sessions, all I can find is a --timeout argument.

**Comment by teodesian** [comment]
Inside of your selenium server's node.json (running a grid), you would put in the following:

  "configuration" :
  {
    "cleanUpCycle":2000
  }
Or run the selenium jar with the -cleanupCycle parameter.
